FROM golang:1.25.4-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /app/bin/server ./cmd/server

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
WORKDIR /app

COPY --from=builder /app/bin/server .
COPY --from=builder /app/configs ./configs

ENV APP_ENV=production
ENV APP_PORT=8080

EXPOSE 8080

CMD ["./server"]
