basePath: /
definitions:
  book.CreateBookNoteReq:
    properties:
      bookId:
        type: integer
      id:
        type: integer
      note:
        type: string
    required:
    - bookId
    - note
    type: object
  book.TTSInput:
    properties:
      languageCode:
        type: string
      ssmlGender:
        type: string
      text:
        type: string
    type: object
  book.TransInput:
    properties:
      data:
        type: string
      language:
        type: string
    type: object
  book.UpdateBookNoteReq:
    properties:
      note:
        type: string
    required:
    - note
    type: object
  data.Book:
    properties:
      author:
        type: string
      category:
        type: string
      coverUrl:
        type: string
      createdAt:
        type: string
      desc:
        type: string
      fileType:
        type: string
      id:
        type: integer
      isbn:
        type: string
      key:
        type: string
      language:
        type: string
      publishDate:
        type: string
      publisher:
        type: string
      title:
        type: string
      updatedAt:
        type: string
      url:
        type: string
    type: object
  data.BookReadingPos:
    properties:
      bookId:
        type: integer
      createdAt:
        type: string
      id:
        type: integer
      lastPosition:
        type: string
      process:
        type: number
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  data.Category:
    properties:
      createdAt:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  home.BannerItem:
    properties:
      author:
        type: string
      coverUrl:
        type: string
      desc:
        type: string
      id:
        type: integer
      isFavourite:
        type: boolean
      title:
        type: string
    type: object
  home.HomeResponse:
    properties:
      banners:
        items:
          $ref: '#/definitions/home.BannerItem'
        type: array
      categories:
        items:
          $ref: '#/definitions/data.Category'
        type: array
    type: object
  home.HomepageSection:
    properties:
      items:
        items:
          $ref: '#/definitions/data.Book'
        type: array
      title:
        type: string
      total:
        type: integer
    type: object
  user.LoginReq:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  user.UpdateProfileReq:
    properties:
      avatar:
        type: string
      language:
        type: string
      name:
        type: string
      offset:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is SericaMind backend api service
  title: SericaMind Backend Service
  version: 1.0.0
paths:
  /v1/client/authors:
    get:
      parameters:
      - description: 筛选名称
        in: query
        name: name
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取作者列表
      tags:
      - Book
  /v1/client/authors/{name}/books:
    get:
      parameters:
      - description: 作者名
        in: path
        name: name
        required: true
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取作者下书籍
      tags:
      - Book
  /v1/client/book-notes:
    get:
      parameters:
      - description: 书籍ID
        in: query
        name: bookId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      security:
      - BearerAuth: []
      summary: 获取书籍笔记列表
      tags:
      - Book Notes
    post:
      consumes:
      - application/json
      parameters:
      - description: 笔记内容
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/book.CreateBookNoteReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 创建/更新书籍笔记
      tags:
      - Book Notes
  /v1/client/book-notes/{id}:
    delete:
      parameters:
      - description: 笔记ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      summary: 删除书籍笔记
      tags:
      - Book Notes
    patch:
      consumes:
      - application/json
      parameters:
      - description: 笔记ID
        in: path
        name: id
        required: true
        type: integer
      - description: 笔记内容
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/book.UpdateBookNoteReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 更新书籍笔记
      tags:
      - Book Notes
  /v1/client/books:
    get:
      description: 分页获取书籍
      parameters:
      - description: 搜索关键词
        in: query
        name: keyword
        type: string
      - default: 1
        description: 页码
        in: query
        name: pageIndex
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: pageSize
        type: integer
      - description: 排序
        in: query
        name: order
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取书籍列表
      tags:
      - Book
  /v1/client/books/{id}:
    get:
      parameters:
      - description: 书籍ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取书籍详情
      tags:
      - Book
  /v1/client/booksKey:
    get:
      description: 返回加密后的书籍密钥
      parameters:
      - description: 书籍ID
        in: query
        name: bookId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 获取书籍AES密钥
      tags:
      - BooksKey
  /v1/client/categories:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Category'
            type: array
      summary: 获取分类列表
      tags:
      - Book
  /v1/client/categories/{id}:
    get:
      parameters:
      - description: 分类ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.Category'
      summary: 获取单个分类
      tags:
      - Book
  /v1/client/categories/{id}/books:
    get:
      parameters:
      - description: 分类ID
        in: path
        name: id
        required: true
        type: integer
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取分类下书籍
      tags:
      - Book
  /v1/client/categories/all:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/data.Category'
            type: array
      summary: 获取所有分类
      tags:
      - Book
  /v1/client/home:
    get:
      description: 获取首页 Banner 和分类
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/home.HomeResponse'
      summary: 首页数据
      tags:
      - Home
  /v1/client/homepage:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/home.HomepageSection'
            type: array
      summary: 首页栏目
      tags:
      - Home
  /v1/client/login:
    post:
      consumes:
      - application/json
      description: 通过邮箱登录
      parameters:
      - description: 登录信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户登录
      tags:
      - User
  /v1/client/publishers:
    get:
      parameters:
      - description: 筛选名称
        in: query
        name: name
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取出版社列表
      tags:
      - Book
  /v1/client/publishers/{name}/books:
    get:
      parameters:
      - description: 出版社名
        in: path
        name: name
        required: true
        type: string
      - default: 1
        description: 页码
        in: query
        name: page
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取出版社下书籍
      tags:
      - Book
  /v1/client/reading-pos:
    get:
      parameters:
      - description: 书籍ID
        in: query
        name: bookId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/data.BookReadingPos'
      security:
      - BearerAuth: []
      summary: 获取阅读进度
      tags:
      - Book
    post:
      consumes:
      - application/json
      parameters:
      - description: 阅读进度
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/data.BookReadingPos'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      summary: 上报阅读进度
      tags:
      - Book
  /v1/client/search:
    get:
      parameters:
      - description: 搜索关键词
        in: query
        name: keyword
        type: string
      - default: 1
        description: 页码
        in: query
        name: pageIndex
        type: integer
      - default: 20
        description: 每页数量
        in: query
        name: pageSize
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 搜索书籍
      tags:
      - Book
  /v1/client/search/history:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      security:
      - BearerAuth: []
      summary: 获取搜索历史
      tags:
      - Search
  /v1/client/search/hot:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              additionalProperties: true
              type: object
            type: array
      summary: 获取热门搜索
      tags:
      - Search
  /v1/client/selection:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: 获取筛选选项
      tags:
      - Book
  /v1/client/text-to-speech:
    post:
      consumes:
      - application/json
      parameters:
      - description: TTS参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/book.TTSInput'
      produces:
      - audio/mpeg
      responses:
        "200":
          description: OK
          schema:
            type: file
      summary: AWS Polly 文字转语音
      tags:
      - Book
  /v1/client/trans:
    post:
      consumes:
      - application/json
      parameters:
      - description: 翻译参数
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/book.TransInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: AI翻译
      tags:
      - Book
  /v1/client/user/favourites:
    get:
      description: 分页获取当前用户的收藏书籍
      parameters:
      - default: 1
        description: 页码
        in: query
        name: pageIndex
        type: integer
      - default: 12
        description: 每页数量
        in: query
        name: pageSize
        type: integer
      - default: true
        description: 是否倒序
        in: query
        name: desc
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 获取收藏列表
      tags:
      - User
  /v1/client/user/profile:
    get:
      description: 获取当前登录用户信息
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: 获取用户信息
      tags:
      - User
    patch:
      consumes:
      - application/json
      parameters:
      - description: 更新信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.UpdateProfileReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: boolean
            type: object
      security:
      - BearerAuth: []
      summary: 更新用户信息
      tags:
      - User
  /v1/client/user/register:
    post:
      consumes:
      - application/json
      description: 通过邮箱注册/登录
      parameters:
      - description: 注册信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/user.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 用户注册
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
